#!/bin/sh -e
echo "Hello, Dave."
#########################
# variables

MY_DIR=$(dirname $0)
echo "MY_DIR=$MY_DIR"

SCRIPT_FILE=$(basename $0)
ME="$MY_DIR/$SCRIPT_FILE"
echo "ME=$ME"

NOW=$(date -u)
echo "NOW=$NOW"

source $MY_DIR/util.sh
echo "Sourced $MY_DIR/util.sh"



########################
# shell setup
if [ $SHELL != "/usr/bin/zsh" ] && [ $SHELL != "/bin/zsh" ]; then
    echo "Setting default shell to zsh "
    chsh -s /usr/bin/zsh
else 
    echo "Shell was already /usr/bin/zsh"    
fi

# https://unix.stackexchange.com/questions/212183/how-do-i-check-if-a-variable-exists-in-an-if-statement

if [ -d $HOME/.oh-my-zsh ]; then 
    echo "It appears oh-my-zsh is already installed."
else
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

theme_dir=~/.oh-my-zsh/custom/themes/powerlevel9k
if [ ! -d $theme_dir ]; then
    echo "Getting powerlevel9k from git.."
    git clone https://github.com/bhilburn/powerlevel9k.git $theme_dir
else
    echo "Powerlevel9k was already installed."
fi

########################
# append shell-init.sh

# appends $1 to interesting shell files
function append_to_shell_rc_files() {
    NOTE="# Added by $ME $NOW"
    maybe_append ~/.bashrc "$NOTE" "$1"
    maybe_append ~/.zshrc "$NOTE" "$1" 
}

# append_to_shell_rc_files "source ~/dotfiles/shell-init.sh"

if [ ! -f ~/.vimrc ]; then 
    touch ~/.vimrc
fi

# managing vim completely via symlink for now
# maybe_append ~/.vimrc "\" Added by $ME $NOW " "source $MY_DIR/vimrc"

########################
# global gitignore
#if [ ! -f ~/.gitignore_global ]; then 
#    cp $MY_DIR/templates/gitignore_global ~/.gitignore_global
#    echo "Copied default ~/.gitignore_global"
#else
#    echo "~/.gitignore_global already exists..."
#fi

echo "Configuring git to use ~/.gitignore_global"
git config --global core.excludesfile ~/.gitignore_global

echo "Done."
