#!/bin/bash -e
ME=`readlink -f $0`
# $1:  the file in question 
# $2:  the text to be appended it it doesn't already exist
function append_if_not_contains() {
if [ -f $1 ]; then
    if  grep -q -F "$2" $1; then 
        echo "'$2' already present in $1"
    else
    	echo -e "\n# Added by $ME\n$2\n" >> $1
	echo "Appended '$2' to $1"
    fi
else
    echo "Skipping $1 because it doesn't exist..."
fi
}

function append_shell_init() {
LINE='source ~/dotfiles/shell-init.sh'
append_if_not_contains ~/.bashrc "$LINE"
append_if_not_contains ~/.zshrc "$LINE"
}

append_shell_init
