#!/bin/sh -e
ME=$(readlink -f $0)
MY_DIR=$(dirname $ME)
source $MY_DIR/util.sh

echo "Searching for files in $MY_DIR/home"

cd $MY_DIR/home

for file in *; do 
    echo "* Working on $file"
    
    symlink="$HOME/.$file"
    target=$(readlink -f $file)

    echo "Symlink $symlink should point to $target"
    
    if [ -L $symlink ]; then 
        echo "$symlink is already a symlink"
    else 
        if [ -f $symlink ]; then 
            new_name="$symlink.old-dotfile"
            echo "$symlink is a regular file, renaming to $new_name"
            mv "$symlink" "$new_name"
        fi
        echo "linking $symlink to $target" 
        ln -s "$target" "$symlink"
    fi

done

echo "Done."

