#!/bin/bash -e

# install useful packages
pacman -S --needed --noconfirm chromium vim emacs zsh ocaml opam htop xclip powerline-fonts awesome-terminal-fonts

# disable anoying pc speaker, if it is enabled
if grep -q pcspkr /proc/modules; then 
    rmmod pcspkr
fi

