#!/bin/sh -e
MY_DIR=$(dirname $0)
source $MY_DIR/util.sh

echo "Searching for files in $MY_DIR/home"

cd $MY_DIR/home

for f in *; do 
    target=$MY_DIR/home/$f
    echo "* Working on $target"
    
    symlink="$HOME/.$f"

    echo "Symlink $symlink should point to $target"
    
    if [ -L $symlink ]; then 
        echo "$symlink is already a symlink"
    else 
        if [ -f $symlink ]; then 
            new_name="$symlink.old-dotfile"
            echo "$symlink is a regular file, renaming to $new_name"
            mv "$symlink" "$new_name"
        fi
        echo "linking $symlink to $target" 
        ln -s "$target" "$symlink"
    fi
done

echo "Done."

