#!/bin/sh -e

plug_dir=~/.vim/autoload/plug.vim


if [ -f $plug_dir ]; then 
    echo "$plug_dir already exists, so not installing vim-plug."
else 
    echo "Downloading vim.plug"
    curl -fLo $plug_dir --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo "NOTE:  You will need to run vim-plug's 'PlugInstall' command to actually install your plugins."
